name: immudb examples CLI
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      immudb:
        image: codenotary/immudb:latest
        ports:
        - 3322:3322
    steps:
    - uses: actions/checkout@v1
    - name: Run examples
      uses: docker://codenotary/immuclient:latest
      with:
        entrypoint: /bin/bash
        args: -c "for i in $GITHUB_WORKSPACE/cli/*.sh; do PATH=$PATH:/app source $i; done"
      env:
        IMMUCLIENT_IMMUDB_ADDRESS: immudb
    - name: Run linter (shellcheck)
      run : |
        sudo apt-get install -y shellcheck
      working-directory: ./cli
