name: immudb examples Node
on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      immudb:
        image: codenotary/immudb:latest
        ports:
        - 3322:3322
    steps:
    - name: Setup runner for Node
      run: |
        sudo apt-get update
        sudo apt-get -y install nodejs npm
    - uses: actions/checkout@v1
    - name: Run examples
      run: |
        npm install
      working-directory: ./node
    - name: Run examples
      run: |
        for f in *.ts
        do
         echo "Processing $f"
         npm run ${f%.*}
        done
      working-directory: ./node
