name: immudb examples Python

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      immudb:
        image: codenotary/immudb:latest
        ports:
        - 3322:3322
    steps:
    - uses: actions/checkout@v1
    - name: Setup runner for Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
    - name: Install Python SDK
      run: |
        pip install immudb-py
    - name: Run examples
      run: |
        for f in *.py
        do
         echo "Processing $f"
         python "$f"
         # force index to be up to date
         python -c "from immudb.client import ImmudbClient; c= ImmudbClient(); c.login('immudb', 'immudb'); s = c.currentState(); c.scan(None, b'dummy', True, 1, sinceTx=s.txId)"
        done
      working-directory: ./python
    - name: Run linter (pep8)
      run : |
        pip install autopep8
        export PATH="$HOME/.local/bin":$PATH
        autopep8 --exit-code --diff *.py
      working-directory: ./python
